"use client"

import { ActivityIcon, CircleAlertIcon, PlusIcon, RefreshCwIcon, Settings2Icon, ShieldCheckIcon, Trash2Icon, UsersIcon } from "lucide-react"
import { useRouter, useSearchParams } from "next/navigation"
import { Suspense, useEffect, useState } from "react"
import { toast } from "sonner"

import { AppShell } from "@/components/app-shell"
import { MetricCard } from "@/components/metric-card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { useAuth } from "@/lib/auth-context"
import { adminApi } from "@/lib/admin-api"
import type { AdminHealth, AdminStats, AdminUserListQuery, AdminUserPage, InviteCode, RegistrationSettings, UserRole } from "@/lib/types"

type Tab = "overview" | "users" | "settings"
const emptyQuery: AdminUserListQuery = { page: 1, pageSize: 15, search: "", account: "all", credential: "all", health: "all" }

export default function AdminPage() {
  return <Suspense fallback={<div className="min-h-dvh bg-muted/35" />}><AdminPageContent /></Suspense>
}

function AdminPageContent() {
  const router = useRouter(); const searchParams = useSearchParams(); const { currentUser, fetchMe } = useAuth()
  const tab = (["overview", "users", "settings"].includes(searchParams.get("tab") ?? "") ? searchParams.get("tab") : "overview") as Tab
  const [stats, setStats] = useState<AdminStats | null>(null); const [health, setHealth] = useState<AdminHealth | null>(null); const [userPage, setUserPage] = useState<AdminUserPage | null>(null); const [query, setQuery] = useState(emptyQuery); const [settings, setSettings] = useState<RegistrationSettings | null>(null); const [invites, setInvites] = useState<InviteCode[]>([]); const [loading, setLoading] = useState(false)
  const [createOpen, setCreateOpen] = useState(false); const [form, setForm] = useState({ username: "", password: "", role: "user" as UserRole })

  const setTab = (next: Tab) => router.replace(next === "overview" ? "/admin" : `/admin?tab=${next}`)
  async function loadOverview() { const [nextStats, nextHealth] = await Promise.all([adminApi.stats(), adminApi.health()]); setStats(nextStats); setHealth(nextHealth) }
  async function loadUsers(nextQuery = query) { const page = await adminApi.users(nextQuery); setUserPage(page); setQuery({ ...nextQuery, page: page.page, pageSize: page.pageSize }) }
  async function loadSettings() { const [nextSettings, nextInvites] = await Promise.all([adminApi.settings(), adminApi.invites()]); setSettings(nextSettings); setInvites(Array.isArray(nextInvites) ? nextInvites : []) }
  async function load() { setLoading(true); try { if (tab === "overview") await loadOverview(); if (tab === "users") await loadUsers(); if (tab === "settings") await loadSettings() } catch (reason) { toast.error((reason as Error).message) } finally { setLoading(false) } }
  useEffect(() => { void (async () => { const user = currentUser ?? await fetchMe(); if (!user) return router.replace("/login"); if (user.role !== "admin") router.replace("/dashboard"); else await load() })() // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tab])
  async function createUser(event: React.FormEvent) { event.preventDefault(); if (form.username.trim().length < 3 || form.password.length < 8) return toast.error("用户名至少 3 位，密码至少 8 位"); try { await adminApi.createUser({ ...form, username: form.username.trim() }); setCreateOpen(false); setForm({ username: "", password: "", role: "user" }); toast.success("用户已创建"); await loadUsers({ ...query, page: 1 }) } catch (reason) { toast.error((reason as Error).message) } }
  const titles = { overview: ["Operations overview", "运营总览", "最近 24 小时系统运行、设备请求和当前待处理问题。"], users: ["Account directory", "用户管理", "查看账户、扫码凭据、设备额度和当前健康状态。"], settings: ["System policies", "系统设置", "管理注册入口、新账户默认权限和长期邀请码。"] } as const
  return <AppShell title={titles[tab][1]} description={titles[tab][2]} actions={<div className="flex gap-2"><Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogTrigger render={<Button><PlusIcon />创建用户</Button>} /><DialogContent><DialogHeader><DialogTitle>创建用户</DialogTitle><DialogDescription>普通用户管理自己的扫码登录和充电桩；管理员进入运营中心维护账户与系统策略。</DialogDescription></DialogHeader><form onSubmit={createUser}><FieldGroup><Field><FieldLabel htmlFor="new-username">用户名</FieldLabel><Input id="new-username" value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} /></Field><Field><FieldLabel htmlFor="new-password">初始密码</FieldLabel><Input id="new-password" type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} /></Field><Field><FieldLabel htmlFor="new-role">角色</FieldLabel><select id="new-role" className="h-8 rounded-lg border bg-background px-2.5 text-sm" value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value as UserRole })}><option value="user">普通用户</option><option value="admin">管理员</option></select></Field><DialogFooter><Button type="button" variant="outline" onClick={() => setCreateOpen(false)}>取消</Button><Button type="submit">确认创建</Button></DialogFooter></FieldGroup></form></DialogContent></Dialog><Button variant="outline" disabled={loading} onClick={() => void load()}><RefreshCwIcon className={loading ? "animate-spin" : ""} />刷新数据</Button></div>}>
    <Tabs value={tab} onValueChange={(value) => setTab(value as Tab)}><TabsList className="mb-6"><TabsTrigger value="overview"><ActivityIcon />运营总览</TabsTrigger><TabsTrigger value="users"><UsersIcon />用户管理</TabsTrigger><TabsTrigger value="settings"><Settings2Icon />系统设置</TabsTrigger></TabsList></Tabs>
    {tab === "overview" && <Overview stats={stats} health={health} onUsers={() => setTab("users")} />}{tab === "users" && <Users page={userPage} query={query} load={loadUsers} />}{tab === "settings" && settings && <Settings settings={settings} setSettings={setSettings} invites={invites} reload={loadSettings} />}
  </AppShell>
}

function Overview({ stats, health, onUsers }: { stats: AdminStats | null; health: AdminHealth | null; onUsers: () => void }) { const overview = stats?.overview; return <div className="space-y-6"><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="待处理问题" value={overview?.openIssues ?? 0} detail="需要关注的异常" icon={CircleAlertIcon} /><MetricCard label="远端成功率" value={Math.round(overview?.remoteSuccessRate ?? 0)} detail="近期开奖" icon={ActivityIcon} /><MetricCard label="活跃用户" value={overview?.activeUsers ?? 0} detail="近期有访问的账户" icon={UsersIcon} /><MetricCard label="管理设备" value={overview?.managedDevices ?? 0} detail="系统中的充电桩" icon={ShieldCheckIcon} /><MetricCard label="离线端口" value={overview?.offlinePorts ?? 0} detail="需要复查设备状态" icon={CircleAlertIcon} /></section><Card className="shadow-none"><CardHeader><CardTitle className="text-base">服务健康</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3">{(["charge", "database", "yyb"] as const).map((name) => <div key={name} className="rounded-lg border p-4"><p className="text-sm font-medium">{{ charge: "充电服务", database: "数据库", yyb: "扫码服务" }[name]}</p><Badge className="mt-3" variant={health?.[name].state === "healthy" ? "secondary" : "destructive"}>{health?.[name].state ?? "检查中"}</Badge><p className="mt-2 text-xs text-muted-foreground">{health?.[name].message ?? "正在加载服务状态"}</p></div>)}</CardContent></Card><Card className="shadow-none"><CardHeader className="flex-row items-center justify-between"><CardTitle className="text-base">最近异常</CardTitle><Button variant="outline" size="sm" onClick={onUsers}>查看用户</Button></CardHeader><CardContent>{stats?.exceptions?.length ? <div className="space-y-2">{stats.exceptions.slice(0, 8).map((issue) => <div key={issue.id} className="rounded-lg border p-3"><p className="text-sm font-medium">{issue.username} · {issue.type}</p><p className="mt-1 text-xs text-muted-foreground">{issue.message}</p></div>)}</div> : <p className="text-sm text-muted-foreground">暂无近期异常。</p>}</CardContent></Card></div> }

function Users({ page, query, load }: { page: AdminUserPage | null; query: AdminUserListQuery; load: (query?: AdminUserListQuery) => Promise<void> }) { const [search, setSearch] = useState(query.search); async function update(id: string, payload: Parameters<typeof adminApi.updateUser>[1]) { try { await adminApi.updateUser(id, payload); toast.success("用户已更新"); await load() } catch (reason) { toast.error((reason as Error).message) } } return <div className="space-y-4"><Card className="shadow-none"><CardContent className="flex flex-col gap-3 p-4 sm:flex-row"><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="用户名搜索" /><select className="h-8 rounded-lg border bg-background px-2.5 text-sm" value={query.account} onChange={(event) => void load({ ...query, account: event.target.value as AdminUserListQuery["account"], page: 1 })}><option value="all">所有账户</option><option value="enabled">仅已启用</option><option value="disabled">仅已停用</option></select><Button onClick={() => void load({ ...query, search, page: 1 })}>搜索</Button></CardContent></Card><div className="grid gap-3">{page?.items.map((summary) => <Card key={summary.user.id} className="shadow-none"><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{summary.user.username} <Badge variant={summary.user.enabled ? "secondary" : "destructive"}>{summary.user.enabled ? "已启用" : "已停用"}</Badge></p><p className="mt-1 text-xs text-muted-foreground">{summary.user.role === "admin" ? "管理员" : "普通用户"} · 设备额度 {summary.user.deviceLimit} · 凭据 {summary.credential.state}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => void update(summary.user.id, { enabled: !summary.user.enabled })}>{summary.user.enabled ? "停用" : "启用"}</Button><Button size="sm" variant="outline" onClick={() => void update(summary.user.id, { refreshEnabled: !summary.user.refreshEnabled })}>{summary.user.refreshEnabled ? "关闭刷新" : "开启刷新"}</Button><Button size="sm" variant="destructive" onClick={() => { if (window.confirm(`删除 ${summary.user.username}？`)) void adminApi.removeUser(summary.user.id).then(() => load()).catch((reason) => toast.error(reason.message)) }}><Trash2Icon />删除</Button></div></CardContent></Card>)}{page && !page.items.length && <Card><CardContent className="p-10 text-center text-sm text-muted-foreground">没有匹配的用户。</CardContent></Card>}</div>{page && <div className="flex items-center justify-between"><p className="text-xs text-muted-foreground">共 {page.total} 位用户，第 {page.page}/{page.totalPages} 页</p><div className="flex gap-2"><Button size="sm" variant="outline" disabled={page.page <= 1} onClick={() => void load({ ...query, page: page.page - 1 })}>上一页</Button><Button size="sm" variant="outline" disabled={page.page >= page.totalPages} onClick={() => void load({ ...query, page: page.page + 1 })}>下一页</Button></div></div>}</div> }

function Settings({ settings, setSettings, invites, reload }: { settings: RegistrationSettings; setSettings: (settings: RegistrationSettings) => void; invites: InviteCode[]; reload: () => Promise<void> }) { async function save(event: React.FormEvent) { event.preventDefault(); try { setSettings(await adminApi.saveSettings(settings)); toast.success("系统设置已保存") } catch (reason) { toast.error((reason as Error).message) } } return <div className="grid gap-6 lg:grid-cols-2"><Card className="shadow-none"><CardHeader><CardTitle className="text-base">注册策略</CardTitle></CardHeader><CardContent><form onSubmit={save}><FieldGroup>{([['openRegistration','开放自助注册'],['inviteRequired','注册需要邀请码'],['defaultRefreshEnabled','新账户默认允许刷新']] as const).map(([key,label]) => <label key={key} className="flex items-center justify-between rounded-lg border p-3 text-sm"><span>{label}</span><input type="checkbox" checked={settings[key]} onChange={(event) => setSettings({ ...settings, [key]: event.target.checked })} /></label>)}<Field><FieldLabel htmlFor="device-limit">默认设备额度</FieldLabel><Input id="device-limit" type="number" value={settings.defaultDeviceLimit} onChange={(event) => setSettings({ ...settings, defaultDeviceLimit: Number(event.target.value) })} /></Field><Field><FieldLabel htmlFor="retention">统计保留天数</FieldLabel><Input id="retention" type="number" value={settings.statsRetentionDays} onChange={(event) => setSettings({ ...settings, statsRetentionDays: Number(event.target.value) })} /></Field><Button type="submit">保存设置</Button></FieldGroup></form></CardContent></Card><Card className="shadow-none"><CardHeader className="flex-row items-center justify-between"><CardTitle className="text-base">邀请码</CardTitle><Button size="sm" onClick={() => void adminApi.createInvite().then(reload).catch((reason) => toast.error(reason.message))}><PlusIcon />生成邀请码</Button></CardHeader><CardContent className="space-y-2">{invites.map((invite) => <div key={invite.id} className="flex items-center justify-between gap-3 rounded-lg border p-3"><div><p className="font-mono text-sm">{invite.code}</p><p className="mt-1 text-xs text-muted-foreground">已使用 {invite.usedCount} 次{invite.expiresAt ? ` · 到期 ${new Date(invite.expiresAt).toLocaleDateString("zh-CN")}` : ""}</p></div><Button size="sm" variant="ghost" onClick={() => void adminApi.removeInvite(invite.id).then(reload).catch((reason) => toast.error(reason.message))}><Trash2Icon /></Button></div>)}{!invites.length && <p className="text-sm text-muted-foreground">暂无邀请码。</p>}</CardContent></Card></div> }
