/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取管理员运营趋势 */
        get: operations["getAdminTrends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/trends.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 导出管理员运营趋势 CSV */
        get: operations["exportAdminTrendsCSV"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notification-preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户的通知偏好 */
        get: operations["getNotificationPreference"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 更新通知偏好 */
        patch: operations["updateNotificationPreference"];
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页获取当前用户的站内通知 */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 当前用户通知 ID */
                notificationId: components["parameters"]["NotificationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 将单条通知标记为已读 */
        post: operations["markNotificationRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 将当前用户的全部未读通知标记为已读 */
        post: operations["markAllNotificationsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/resolved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 清理当前用户已经解决的通知 */
        delete: operations["deleteResolvedNotifications"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/piles/{deviceId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取充电桩历史分析 */
        get: operations["getDeviceHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/piles/{deviceId}/ports/{portId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取单个充电口历史分析 */
        get: operations["getPortHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watch-overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户的关注额度与后台提醒策略摘要 */
        get: operations["getWatchOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watch-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户的全部关注规则 */
        get: operations["listWatchRules"];
        put?: never;
        /** 为充电桩创建空闲提醒规则 */
        post: operations["createWatchRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watch-rules/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 当前用户关注规则 ID */
                ruleId: components["parameters"]["WatchRuleId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除关注规则 */
        delete: operations["deleteWatchRule"];
        options?: never;
        head?: never;
        /** 更新关注规则状态和生效时段 */
        patch: operations["updateWatchRule"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminTrendPoint: {
            activeUsers: number;
            /** Format: date-time */
            end: string;
            offlinePorts: number;
            remoteAttempts: number;
            remoteFailures: number;
            remoteSuccesses: number;
            /** Format: double */
            remoteSuccessRate: number | null;
            requests: number;
            /** Format: date-time */
            start: string;
        };
        /**
         * @default 24h
         * @enum {string}
         */
        AdminTrendRange: "24h" | "7d" | "30d";
        AdminTrendsResponse: {
            points: components["schemas"]["AdminTrendPoint"][];
            summary: components["schemas"]["AdminTrendSummary"];
            /** Format: date-time */
            updatedAt: string;
            window: components["schemas"]["AdminTrendWindow"];
        };
        AdminTrendSummary: {
            activeUsers: number;
            offlinePorts: number;
            remoteAttempts: number;
            remoteFailures: number;
            remoteSuccesses: number;
            /** Format: double */
            remoteSuccessRate: number | null;
            requests: number;
        };
        AdminTrendWindow: {
            /** @enum {string} */
            bucketUnit: "hour" | "day";
            /** Format: date-time */
            end: string;
            range: components["schemas"]["AdminTrendRange"];
            /** Format: date-time */
            start: string;
            timezone: string;
        };
        CodedErrorResponse: {
            /** @enum {string} */
            code: "DEVICE_ID_INVALID" | "PORT_ID_INVALID" | "HISTORY_QUERY_INVALID" | "HISTORY_NOT_FOUND" | "HISTORY_RANGE_TOO_LARGE" | "HISTORY_UNAVAILABLE" | "ADMIN_TREND_QUERY_INVALID" | "ADMIN_TRENDS_UNAVAILABLE" | "WATCH_RULE_INVALID" | "WATCH_TARGET_NOT_FOUND" | "WATCH_RULE_NOT_FOUND" | "WATCH_RULE_CONFLICT" | "WATCH_PILE_LIMIT_REACHED" | "WATCH_UNAVAILABLE" | "NOTIFICATION_PREFERENCE_INVALID" | "NOTIFICATION_QUERY_INVALID" | "NOTIFICATION_NOT_FOUND" | "NOTIFICATION_UNAVAILABLE";
            error: string;
        };
        DeletedCount: {
            /** Format: int64 */
            deleted: number;
        };
        DeviceHistoryResponse: {
            busiestHours: components["schemas"]["HistoryHourInsight"][];
            daily: components["schemas"]["HistoryDailyPoint"][];
            device: components["schemas"]["HistoryDevice"];
            heatmap: components["schemas"]["HistoryHeatmapCell"][];
            historyNotice: string;
            /** Format: date-time */
            historyStartedAt?: string;
            metrics: components["schemas"]["PortHistoryMetrics"];
            ports: components["schemas"]["PortHistorySummary"][];
            quietSuggestion?: components["schemas"]["HistoryHourInsight"];
            window: components["schemas"]["HistoryWindow"];
        };
        ErrorResponse: {
            error: string;
        };
        HistoryDailyPoint: {
            /** Format: date */
            date: string;
            metrics: components["schemas"]["PortHistoryMetrics"];
        };
        HistoryDevice: {
            address: string;
            id: string;
            name: string;
            number: string;
        };
        HistoryHeatmapCell: {
            hour: number;
            /** Format: int64 */
            idleSeconds: number;
            /** Format: int64 */
            inUseSeconds: number;
            /** Format: double */
            occupancyPercent: number | null;
            /** Format: int64 */
            offlineSeconds: number;
            sampleDates: number;
            sampleSufficient: boolean;
            weekday: number;
        };
        HistoryHourInsight: {
            hour: number;
            /** Format: double */
            occupancyPercent: number;
            sampleDates: number;
            weekday: number;
        };
        /**
         * @default 7d
         * @enum {string}
         */
        HistoryRange: "24h" | "7d" | "30d";
        /** @enum {string} */
        HistorySampleState: "no_data" | "insufficient" | "partial" | "sufficient";
        HistoryWindow: {
            /** Format: date-time */
            end: string;
            range: components["schemas"]["HistoryRange"];
            /** Format: date-time */
            start: string;
            timezone: string;
        };
        Notification: {
            /** Format: date-time */
            createdAt: string;
            deviceId?: string;
            id: string;
            message: string;
            portId?: number | null;
            /** Format: date-time */
            readAt?: string | null;
            /** Format: date-time */
            resolvedAt?: string | null;
            severity: components["schemas"]["NotificationSeverity"];
            /** Format: int64 */
            sourceEventId?: number | null;
            title: string;
            type: components["schemas"]["NotificationType"];
            userId: string;
        };
        NotificationPage: {
            items: components["schemas"]["Notification"][];
            nextCursor?: string;
            unreadCount: number;
        };
        NotificationPreference: {
            browserEnabled: boolean;
            quietEndMinute: number;
            quietHoursEnabled: boolean;
            quietStartMinute: number;
            timezone: string;
            /** Format: date-time */
            updatedAt: string;
            userId: string;
        };
        NotificationPreferenceUpdateRequest: {
            browserEnabled?: boolean;
            quietEndMinute?: number;
            quietHoursEnabled?: boolean;
            quietStartMinute?: number;
            timezone?: string;
        };
        /** @enum {string} */
        NotificationSeverity: "info" | "warning" | "critical";
        /**
         * @default all
         * @enum {string}
         */
        NotificationStatusFilter: "all" | "unread" | "resolved";
        /** @enum {string} */
        NotificationType: "pile_available" | "credential_expired" | "pile_offline" | "pile_recovered";
        PortHistoryMetrics: {
            /** Format: int64 */
            averageSessionSeconds: number | null;
            completedSessions: number;
            /** Format: int64 */
            gapSeconds: number;
            /** Format: int64 */
            idleSeconds: number;
            /** Format: int64 */
            inUseSeconds: number;
            /** Format: int64 */
            observedSeconds: number;
            /** Format: double */
            occupancyPercent: number | null;
            /** Format: int64 */
            offlineSeconds: number;
            sampleState: components["schemas"]["HistorySampleState"];
        };
        PortHistoryResponse: {
            currentStatus: components["schemas"]["PortStatus"];
            daily: components["schemas"]["HistoryDailyPoint"][];
            device: components["schemas"]["HistoryDevice"];
            historyNotice: string;
            /** Format: date-time */
            historyStartedAt?: string;
            metrics: components["schemas"]["PortHistoryMetrics"];
            portId: number;
            timeline: components["schemas"]["PortHistoryTimelineItem"][];
            timelineTruncated: boolean;
            window: components["schemas"]["HistoryWindow"];
        };
        PortHistorySummary: {
            currentStatus: components["schemas"]["PortStatus"];
            /** Format: date-time */
            historyStartedAt?: string;
            metrics: components["schemas"]["PortHistoryMetrics"];
            portId: number;
        };
        PortHistoryTimelineItem: {
            /** Format: date-time */
            changedAt: string;
            fromStatus?: components["schemas"]["PortStatus"];
            portId: number;
            remainingText?: string;
            toStatus: components["schemas"]["PortStatus"];
            usedSeconds: number;
        };
        /** @enum {string} */
        PortStatus: "idle" | "in_use" | "offline";
        UpdatedCount: {
            /** Format: int64 */
            updated: number;
        };
        WatchOverview: {
            accountRefreshEnabled: boolean;
            backgroundRemindersEnabled: boolean;
            dailyQuotaLimit: number;
            dailyQuotaUsed: number;
            /** Format: date */
            quotaDate: string;
            refreshIntervalMinutes: number;
            reminderPileCount: number;
            reminderPileLimit: number;
            scheduledPowerOffEnabled: boolean;
            scheduledPowerOffEndMinute: number;
            scheduledPowerOffStartMinute: number;
            scheduledPowerOffTimezone: string;
        };
        WatchRule: {
            /** @description 当地时区当天结束分钟；小于起始分钟时表示跨午夜。 */
            activeEndMinute: number;
            /** @description 当地时区当天起始分钟；与结束分钟相同时表示全天。 */
            activeStartMinute: number;
            /** @description 星期位掩码，bit 0 至 bit 6 依次代表周一至周日。 */
            activeWeekdays: number;
            /** Format: date-time */
            createdAt: string;
            deviceId: string;
            enabled: boolean;
            id: string;
            timezone: string;
            /** Format: date-time */
            updatedAt: string;
            userId: string;
        };
        WatchRuleCreateRequest: {
            /** @description 当地时区当天结束分钟；小于起始分钟时表示跨午夜。 */
            activeEndMinute?: number;
            /** @description 当地时区当天起始分钟；与结束分钟相同时表示全天。 */
            activeStartMinute?: number;
            /** @description 星期位掩码，bit 0 至 bit 6 依次代表周一至周日。 */
            activeWeekdays?: number;
            deviceId: string;
            enabled?: boolean;
            timezone?: string;
        };
        WatchRuleUpdateRequest: {
            /** @description 当地时区当天结束分钟；小于起始分钟时表示跨午夜。 */
            activeEndMinute?: number;
            /** @description 当地时区当天起始分钟；与结束分钟相同时表示全天。 */
            activeStartMinute?: number;
            /** @description 星期位掩码，bit 0 至 bit 6 依次代表周一至周日。 */
            activeWeekdays?: number;
            enabled?: boolean;
            timezone?: string;
        };
    };
    responses: {
        /** @description 当前账户不是管理员 */
        AdminRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "admin permission required"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 指标或状态历史聚合暂时不可用 */
        AdminTrendsUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "ADMIN_TRENDS_UNAVAILABLE",
                 *       "error": "运营趋势暂时不可用，请稍后重试"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 设备不属于当前用户、端口不存在或尚无该端口历史 */
        HistoryNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "HISTORY_NOT_FOUND",
                 *       "error": "未找到对应的历史记录"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 所选范围内的状态变化超过单次分析上限 */
        HistoryRangeTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "HISTORY_RANGE_TOO_LARGE",
                 *       "error": "该范围内历史变化过多，请缩短查询范围"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 历史存储或聚合暂时不可用 */
        HistoryUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "HISTORY_UNAVAILABLE",
                 *       "error": "历史数据暂时不可用，请稍后重试"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 趋势范围或时区参数无效 */
        InvalidAdminTrendQuery: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "ADMIN_TREND_QUERY_INVALID",
                 *       "error": "趋势范围或时区参数无效"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 设备 ID、历史范围或时区参数无效 */
        InvalidHistoryQuery: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 设备 ID、端口编号、历史范围或时区参数无效 */
        InvalidPortHistoryQuery: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 请求方法不受支持 */
        MethodNotAllowed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "method not allowed"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 通知不存在或不属于当前用户 */
        NotificationNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOTIFICATION_NOT_FOUND",
                 *       "error": "未找到通知"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 通知偏好、免打扰时间或时区无效 */
        NotificationPreferenceInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOTIFICATION_PREFERENCE_INVALID",
                 *       "error": "通知偏好内容无效"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 通知状态、分页大小或游标无效 */
        NotificationQueryInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOTIFICATION_QUERY_INVALID",
                 *       "error": "通知筛选或分页参数无效"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 通知存储暂时不可用 */
        NotificationUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOTIFICATION_UNAVAILABLE",
                 *       "error": "通知功能暂时不可用，请稍后重试"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 当前账户不是普通用户 */
        OrdinaryUserRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "ordinary user permission required"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 未登录或会话已失效 */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "login required"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 目标已存在，或达到规则/提醒桩数量限制 */
        WatchConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 关注规则字段、星期、时段或时区无效 */
        WatchInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "WATCH_RULE_INVALID",
                 *       "error": "关注规则内容无效"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 规则不存在或不属于当前用户 */
        WatchRuleNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "WATCH_RULE_NOT_FOUND",
                 *       "error": "未找到关注规则"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 充电桩不属于当前用户或端口不存在 */
        WatchTargetNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "WATCH_TARGET_NOT_FOUND",
                 *       "error": "未找到当前账户下的充电桩或端口"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 关注规则存储暂时不可用 */
        WatchUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "WATCH_UNAVAILABLE",
                 *       "error": "关注功能暂时不可用，请稍后重试"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description 趋势统计范围；省略时使用 24h */
        AdminTrendRange: components["schemas"]["AdminTrendRange"];
        /** @description 当前用户已绑定的 6–64 位数字设备 ID */
        DeviceId: string;
        /** @description 历史统计范围；省略时使用 7d */
        HistoryRange: components["schemas"]["HistoryRange"];
        /** @description 当前用户通知 ID */
        NotificationId: string;
        /** @description 充电口编号 */
        PortId: number;
        /** @description IANA 时区名称；省略时使用 Asia/Shanghai */
        Timezone: string;
        /** @description 当前用户关注规则 ID */
        WatchRuleId: string;
    };
    requestBodies: never;
    headers: {
        /** @description 包含范围和导出日期的安全 ASCII 文件名 */
        CSVContentDisposition: string;
        /** @description 分析响应包含用户或运营数据，不允许共享或本地缓存 */
        PrivateNoStore: "private, no-store";
    };
    pathItems: never;
}
export type AdminTrendPoint = components['schemas']['AdminTrendPoint'];
export type AdminTrendRange = components['schemas']['AdminTrendRange'];
export type AdminTrendsResponse = components['schemas']['AdminTrendsResponse'];
export type AdminTrendSummary = components['schemas']['AdminTrendSummary'];
export type AdminTrendWindow = components['schemas']['AdminTrendWindow'];
export type CodedErrorResponse = components['schemas']['CodedErrorResponse'];
export type DeletedCount = components['schemas']['DeletedCount'];
export type DeviceHistoryResponse = components['schemas']['DeviceHistoryResponse'];
export type ErrorResponse = components['schemas']['ErrorResponse'];
export type HistoryDailyPoint = components['schemas']['HistoryDailyPoint'];
export type HistoryDevice = components['schemas']['HistoryDevice'];
export type HistoryHeatmapCell = components['schemas']['HistoryHeatmapCell'];
export type HistoryHourInsight = components['schemas']['HistoryHourInsight'];
export type HistoryRange = components['schemas']['HistoryRange'];
export type HistorySampleState = components['schemas']['HistorySampleState'];
export type HistoryWindow = components['schemas']['HistoryWindow'];
export type Notification = components['schemas']['Notification'];
export type NotificationPage = components['schemas']['NotificationPage'];
export type NotificationPreference = components['schemas']['NotificationPreference'];
export type NotificationPreferenceUpdateRequest = components['schemas']['NotificationPreferenceUpdateRequest'];
export type NotificationSeverity = components['schemas']['NotificationSeverity'];
export type NotificationStatusFilter = components['schemas']['NotificationStatusFilter'];
export type NotificationType = components['schemas']['NotificationType'];
export type PortHistoryMetrics = components['schemas']['PortHistoryMetrics'];
export type PortHistoryResponse = components['schemas']['PortHistoryResponse'];
export type PortHistorySummary = components['schemas']['PortHistorySummary'];
export type PortHistoryTimelineItem = components['schemas']['PortHistoryTimelineItem'];
export type PortStatus = components['schemas']['PortStatus'];
export type UpdatedCount = components['schemas']['UpdatedCount'];
export type WatchOverview = components['schemas']['WatchOverview'];
export type WatchRule = components['schemas']['WatchRule'];
export type WatchRuleCreateRequest = components['schemas']['WatchRuleCreateRequest'];
export type WatchRuleUpdateRequest = components['schemas']['WatchRuleUpdateRequest'];
export type ResponseAdminRequired = components['responses']['AdminRequired'];
export type ResponseAdminTrendsUnavailable = components['responses']['AdminTrendsUnavailable'];
export type ResponseHistoryNotFound = components['responses']['HistoryNotFound'];
export type ResponseHistoryRangeTooLarge = components['responses']['HistoryRangeTooLarge'];
export type ResponseHistoryUnavailable = components['responses']['HistoryUnavailable'];
export type ResponseInvalidAdminTrendQuery = components['responses']['InvalidAdminTrendQuery'];
export type ResponseInvalidHistoryQuery = components['responses']['InvalidHistoryQuery'];
export type ResponseInvalidPortHistoryQuery = components['responses']['InvalidPortHistoryQuery'];
export type ResponseMethodNotAllowed = components['responses']['MethodNotAllowed'];
export type ResponseNotificationNotFound = components['responses']['NotificationNotFound'];
export type ResponseNotificationPreferenceInvalid = components['responses']['NotificationPreferenceInvalid'];
export type ResponseNotificationQueryInvalid = components['responses']['NotificationQueryInvalid'];
export type ResponseNotificationUnavailable = components['responses']['NotificationUnavailable'];
export type ResponseOrdinaryUserRequired = components['responses']['OrdinaryUserRequired'];
export type ResponseUnauthenticated = components['responses']['Unauthenticated'];
export type ResponseWatchConflict = components['responses']['WatchConflict'];
export type ResponseWatchInvalid = components['responses']['WatchInvalid'];
export type ResponseWatchRuleNotFound = components['responses']['WatchRuleNotFound'];
export type ResponseWatchTargetNotFound = components['responses']['WatchTargetNotFound'];
export type ResponseWatchUnavailable = components['responses']['WatchUnavailable'];
export type ParameterAdminTrendRange = components['parameters']['AdminTrendRange'];
export type ParameterDeviceId = components['parameters']['DeviceId'];
export type ParameterHistoryRange = components['parameters']['HistoryRange'];
export type ParameterNotificationId = components['parameters']['NotificationId'];
export type ParameterPortId = components['parameters']['PortId'];
export type ParameterTimezone = components['parameters']['Timezone'];
export type ParameterWatchRuleId = components['parameters']['WatchRuleId'];
export type HeaderCsvContentDisposition = components['headers']['CSVContentDisposition'];
export type HeaderPrivateNoStore = components['headers']['PrivateNoStore'];
export type $defs = Record<string, never>;
export interface operations {
    getAdminTrends: {
        parameters: {
            query?: {
                /** @description 趋势统计范围；省略时使用 24h */
                range?: components["parameters"]["AdminTrendRange"];
                /** @description IANA 时区名称；省略时使用 Asia/Shanghai */
                timezone?: components["parameters"]["Timezone"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求量、远端成功率、活跃用户和离线端口趋势 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTrendsResponse"];
                };
            };
            400: components["responses"]["InvalidAdminTrendQuery"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["AdminRequired"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["AdminTrendsUnavailable"];
        };
    };
    exportAdminTrendsCSV: {
        parameters: {
            query?: {
                /** @description 趋势统计范围；省略时使用 24h */
                range?: components["parameters"]["AdminTrendRange"];
                /** @description IANA 时区名称；省略时使用 Asia/Shanghai */
                timezone?: components["parameters"]["Timezone"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 与相同范围趋势接口数值一致的 UTF-8 BOM CSV 文件 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    "Content-Disposition": components["headers"]["CSVContentDisposition"];
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            400: components["responses"]["InvalidAdminTrendQuery"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["AdminRequired"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["AdminTrendsUnavailable"];
        };
    };
    getNotificationPreference: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 浏览器通知意愿与免打扰设置 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreference"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["NotificationUnavailable"];
        };
    };
    updateNotificationPreference: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationPreferenceUpdateRequest"];
            };
        };
        responses: {
            /** @description 更新后的通知偏好 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreference"];
                };
            };
            400: components["responses"]["NotificationPreferenceInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["NotificationUnavailable"];
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                status?: components["schemas"]["NotificationStatusFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 通知分页、下一游标和总未读数量 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPage"];
                };
            };
            400: components["responses"]["NotificationQueryInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["NotificationUnavailable"];
        };
    };
    markNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 当前用户通知 ID */
                notificationId: components["parameters"]["NotificationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已读后的通知 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            404: components["responses"]["NotificationNotFound"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["NotificationUnavailable"];
        };
    };
    markAllNotificationsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 实际更新数量 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdatedCount"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["NotificationUnavailable"];
        };
    };
    deleteResolvedNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 实际删除数量 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedCount"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["NotificationUnavailable"];
        };
    };
    getDeviceHistory: {
        parameters: {
            query?: {
                /** @description 历史统计范围；省略时使用 7d */
                range?: components["parameters"]["HistoryRange"];
                /** @description IANA 时区名称；省略时使用 Asia/Shanghai */
                timezone?: components["parameters"]["Timezone"];
            };
            header?: never;
            path: {
                /** @description 当前用户已绑定的 6–64 位数字设备 ID */
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 设备维度的历史指标、每日趋势、热力图和端口摘要 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceHistoryResponse"];
                };
            };
            400: components["responses"]["InvalidHistoryQuery"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            404: components["responses"]["HistoryNotFound"];
            405: components["responses"]["MethodNotAllowed"];
            422: components["responses"]["HistoryRangeTooLarge"];
            503: components["responses"]["HistoryUnavailable"];
        };
    };
    getPortHistory: {
        parameters: {
            query?: {
                /** @description 历史统计范围；省略时使用 7d */
                range?: components["parameters"]["HistoryRange"];
                /** @description IANA 时区名称；省略时使用 Asia/Shanghai */
                timezone?: components["parameters"]["Timezone"];
            };
            header?: never;
            path: {
                /** @description 当前用户已绑定的 6–64 位数字设备 ID */
                deviceId: components["parameters"]["DeviceId"];
                /** @description 充电口编号 */
                portId: components["parameters"]["PortId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 单个端口的历史指标、每日趋势和最近状态时间线 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortHistoryResponse"];
                };
            };
            400: components["responses"]["InvalidPortHistoryQuery"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            404: components["responses"]["HistoryNotFound"];
            405: components["responses"]["MethodNotAllowed"];
            422: components["responses"]["HistoryRangeTooLarge"];
            503: components["responses"]["HistoryUnavailable"];
        };
    };
    getWatchOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 仅包含当前用户用量和管理员公开给普通用户的提醒策略 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchOverview"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["WatchUnavailable"];
        };
    };
    listWatchRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 按更新时间倒序返回的关注规则 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchRule"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["WatchUnavailable"];
        };
    };
    createWatchRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchRuleCreateRequest"];
            };
        };
        responses: {
            /** @description 已创建的关注规则 */
            201: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchRule"];
                };
            };
            400: components["responses"]["WatchInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            404: components["responses"]["WatchTargetNotFound"];
            405: components["responses"]["MethodNotAllowed"];
            409: components["responses"]["WatchConflict"];
            503: components["responses"]["WatchUnavailable"];
        };
    };
    deleteWatchRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 当前用户关注规则 ID */
                ruleId: components["parameters"]["WatchRuleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 关注规则已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            404: components["responses"]["WatchRuleNotFound"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["WatchUnavailable"];
        };
    };
    updateWatchRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 当前用户关注规则 ID */
                ruleId: components["parameters"]["WatchRuleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchRuleUpdateRequest"];
            };
        };
        responses: {
            /** @description 更新后的关注规则 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchRule"];
                };
            };
            400: components["responses"]["WatchInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            404: components["responses"]["WatchRuleNotFound"];
            405: components["responses"]["MethodNotAllowed"];
            409: components["responses"]["WatchConflict"];
            503: components["responses"]["WatchUnavailable"];
        };
    };
}
