/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取数据库、备份、通知与提醒调度状态 */
        get: operations["getAdminOperations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取系统注册、提醒与保留策略 */
        get: operations["getAdminSettings"];
        /**
         * 更新系统注册、提醒与保留策略
         * @description 修改结果会写入管理员审计日志，并立即唤醒提醒调度器。
         */
        put: operations["updateAdminSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取管理员运营趋势 */
        get: operations["getAdminTrends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/trends.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 导出管理员运营趋势 CSV */
        get: operations["exportAdminTrendsCSV"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notification-channels/wxpusher": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户的 WxPusher 通道状态 */
        get: operations["getWxPusherChannel"];
        put?: never;
        post?: never;
        /**
         * 解除当前用户的本地 WxPusher 绑定
         * @description 删除本地 UID 并取消尚未开始的投递任务，不承诺替用户取消关注 WxPusher 应用或退出接收客户端。
         */
        delete: operations["deleteWxPusherChannel"];
        options?: never;
        head?: never;
        /** 更新 WxPusher 总开关和事件类型偏好 */
        patch: operations["updateWxPusherChannel"];
        trace?: never;
    };
    "/api/notification-channels/wxpusher/bind-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建十分钟有效的 WxPusher 参数二维码绑定会话 */
        post: operations["createWxPusherBindSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notification-channels/wxpusher/bind-sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 当前用户的随机绑定会话 ID */
                sessionId: components["parameters"]["WxPusherBindSessionId"];
            };
            cookie?: never;
        };
        /**
         * 查询当前用户的 WxPusher 绑定进度
         * @description 前端建议每十秒查询一次；后端强制限制向供应商轮询的最短间隔。
         */
        get: operations["getWxPusherBindSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notification-channels/wxpusher/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 为当前用户创建一条受频率限制的 WxPusher 测试投递 */
        post: operations["testWxPusherChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notification-channels/wxpusher/test/recheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 重新查询当前用户最近一条 WxPusher 测试消息的供应商状态
         * @description 仅查询原投递记录，不创建或重新发送消息。已结束或尚未提交到供应商的状态会原样返回。
         */
        post: operations["recheckWxPusherTestDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notification-preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户的通知偏好 */
        get: operations["getNotificationPreference"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 更新通知偏好 */
        patch: operations["updateNotificationPreference"];
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页获取当前用户的通知中心消息 */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 当前用户通知 ID */
                notificationId: components["parameters"]["NotificationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 将单条通知标记为已读 */
        post: operations["markNotificationRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 将当前用户的全部未读通知标记为已读 */
        post: operations["markAllNotificationsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/resolved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 清理当前用户已经解决的通知 */
        delete: operations["deleteResolvedNotifications"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/piles/{deviceId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取充电桩历史分析 */
        get: operations["getDeviceHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/piles/{deviceId}/ports/{portId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取单个充电口历史分析 */
        get: operations["getPortHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watch-overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户的空闲提醒额度与后台策略摘要 */
        get: operations["getWatchOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watch-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户的全部整桩空闲提醒规则 */
        get: operations["listWatchRules"];
        put?: never;
        /** 为充电桩创建空闲提醒规则 */
        post: operations["createWatchRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watch-rules/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 当前用户空闲提醒规则 ID */
                ruleId: components["parameters"]["WatchRuleId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除空闲提醒规则 */
        delete: operations["deleteWatchRule"];
        options?: never;
        head?: never;
        /** 更新空闲提醒规则状态和生效时段 */
        patch: operations["updateWatchRule"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminTrendPoint: {
            activeUsers: number;
            /** Format: date-time */
            end: string;
            offlinePorts: number;
            remoteAttempts: number;
            remoteFailures: number;
            remoteSuccesses: number;
            /** Format: double */
            remoteSuccessRate: number | null;
            requests: number;
            /** Format: date-time */
            start: string;
        };
        /**
         * @default 24h
         * @enum {string}
         */
        AdminTrendRange: "24h" | "7d" | "30d";
        AdminTrendsResponse: {
            points: components["schemas"]["AdminTrendPoint"][];
            summary: components["schemas"]["AdminTrendSummary"];
            /** Format: date-time */
            updatedAt: string;
            window: components["schemas"]["AdminTrendWindow"];
        };
        AdminTrendSummary: {
            activeUsers: number;
            offlinePorts: number;
            remoteAttempts: number;
            remoteFailures: number;
            remoteSuccesses: number;
            /** Format: double */
            remoteSuccessRate: number | null;
            requests: number;
        };
        AdminTrendWindow: {
            /** @enum {string} */
            bucketUnit: "hour" | "day";
            /** Format: date-time */
            end: string;
            range: components["schemas"]["AdminTrendRange"];
            /** Format: date-time */
            start: string;
            timezone: string;
        };
        CodedErrorResponse: {
            /** @enum {string} */
            code: "DEVICE_ID_INVALID" | "PORT_ID_INVALID" | "HISTORY_QUERY_INVALID" | "HISTORY_NOT_FOUND" | "HISTORY_RANGE_TOO_LARGE" | "HISTORY_UNAVAILABLE" | "ADMIN_TREND_QUERY_INVALID" | "ADMIN_TRENDS_UNAVAILABLE" | "WATCH_RULE_INVALID" | "WATCH_TARGET_NOT_FOUND" | "WATCH_RULE_NOT_FOUND" | "WATCH_RULE_CONFLICT" | "WATCH_PILE_LIMIT_REACHED" | "WATCH_UNAVAILABLE" | "NOTIFICATION_PREFERENCE_INVALID" | "NOTIFICATION_QUERY_INVALID" | "NOTIFICATION_NOT_FOUND" | "NOTIFICATION_UNAVAILABLE";
            error: string;
        };
        DeletedCount: {
            /** Format: int64 */
            deleted: number;
        };
        DeviceHistoryResponse: {
            busiestHours: components["schemas"]["HistoryHourInsight"][];
            daily: components["schemas"]["HistoryDailyPoint"][];
            device: components["schemas"]["HistoryDevice"];
            heatmap: components["schemas"]["HistoryHeatmapCell"][];
            historyNotice: string;
            /** Format: date-time */
            historyStartedAt?: string;
            metrics: components["schemas"]["PortHistoryMetrics"];
            ports: components["schemas"]["PortHistorySummary"][];
            quietSuggestion?: components["schemas"]["HistoryHourInsight"];
            window: components["schemas"]["HistoryWindow"];
        };
        ErrorResponse: {
            error: string;
        };
        HistoryDailyPoint: {
            /** Format: date */
            date: string;
            metrics: components["schemas"]["PortHistoryMetrics"];
        };
        HistoryDevice: {
            address: string;
            id: string;
            name: string;
            number: string;
        };
        HistoryHeatmapCell: {
            hour: number;
            /** Format: int64 */
            idleSeconds: number;
            /** Format: int64 */
            inUseSeconds: number;
            /** Format: double */
            occupancyPercent: number | null;
            /** Format: int64 */
            offlineSeconds: number;
            sampleDates: number;
            sampleSufficient: boolean;
            weekday: number;
        };
        HistoryHourInsight: {
            hour: number;
            /** Format: double */
            occupancyPercent: number;
            sampleDates: number;
            weekday: number;
        };
        /**
         * @default 7d
         * @enum {string}
         */
        HistoryRange: "24h" | "7d" | "30d";
        /** @enum {string} */
        HistorySampleState: "no_data" | "insufficient" | "partial" | "sufficient";
        HistoryWindow: {
            /** Format: date-time */
            end: string;
            range: components["schemas"]["HistoryRange"];
            /** Format: date-time */
            start: string;
            timezone: string;
        };
        Notification: {
            /** Format: date-time */
            createdAt: string;
            deviceId?: string;
            id: string;
            /** Format: date-time */
            lastOccurredAt: string;
            message: string;
            occurrenceCount: number;
            portId?: number | null;
            /** Format: date-time */
            readAt?: string | null;
            /** Format: date-time */
            resolvedAt?: string | null;
            severity: components["schemas"]["NotificationSeverity"];
            /** Format: int64 */
            sourceEventId?: number | null;
            title: string;
            type: components["schemas"]["NotificationType"];
            userId: string;
        };
        /** @enum {string} */
        NotificationDeliveryStatus: "pending" | "sending" | "accepted" | "provider_succeeded" | "retry_wait" | "suppressed" | "uncertain" | "failed" | "cancelled";
        NotificationDeliverySummary: {
            /**
             * Format: date-time
             * @description WxPusher API 已受理时间。
             */
            acceptedAt?: string;
            /**
             * Format: date-time
             * @description 投递任务创建时间。
             */
            createdAt: string;
            errorCode?: components["schemas"]["WxPusherErrorCode"];
            id: string;
            isTest: boolean;
            message: string;
            /**
             * Format: date-time
             * @description WxPusher 状态接口确认处理成功的时间，不代表具体接收客户端已展示或已读。
             */
            providerSucceededAt?: string;
            status: components["schemas"]["NotificationDeliveryStatus"];
            /**
             * Format: date-time
             * @description 最近一次本地状态更新或供应商状态查询时间。
             */
            updatedAt: string;
            userState: components["schemas"]["NotificationDeliveryUserState"];
        };
        /**
         * @description 面向用户的投递事实；供应商后续查询未知不会覆盖已经确认的提交成功。
         * @enum {string}
         */
        NotificationDeliveryUserState: "queued" | "submitted" | "processed" | "suppressed" | "failed" | "cancelled" | "unknown";
        NotificationPage: {
            items: components["schemas"]["Notification"][];
            nextCursor?: string;
            unreadCount: number;
        };
        NotificationPreference: {
            browserEnabled: boolean;
            quietEndMinute: number;
            quietHoursEnabled: boolean;
            quietStartMinute: number;
            timezone: string;
            /** Format: date-time */
            updatedAt: string;
            userId: string;
        };
        NotificationPreferenceUpdateRequest: {
            browserEnabled?: boolean;
            quietEndMinute?: number;
            quietHoursEnabled?: boolean;
            quietStartMinute?: number;
            timezone?: string;
        };
        /** @enum {string} */
        NotificationSeverity: "info" | "warning" | "critical";
        /**
         * @description pending 和 resolved 仅包含需要用户处理的登录失效与持续离线问题；信息类通知不进入这两个列表。
         * @default all
         * @enum {string}
         */
        NotificationStatusFilter: "all" | "unread" | "pending" | "resolved";
        /** @enum {string} */
        NotificationType: "pile_available" | "credential_expired" | "pile_offline" | "pile_recovered";
        OperationsStatus: {
            backupMessage: string;
            /** @enum {string} */
            backupState: "healthy" | "degraded" | "unavailable";
            /** Format: date-time */
            checkedAt: string;
            /** Format: int64 */
            databaseSizeBytes: number;
            integrityResult: string;
            /** Format: date-time */
            lastBackupAt?: string | null;
            /** Format: int64 */
            lastBackupSizeBytes?: number;
            metricRetentionDays: number;
            /** Format: int64 */
            metricRows: number;
            notificationRetentionDays: number;
            /** Format: int64 */
            notificationRows: number;
            /** Format: date-time */
            portHistoryNewestAt?: string | null;
            /** Format: date-time */
            portHistoryOldestAt?: string | null;
            portHistoryRetentionDays: number;
            /** Format: int64 */
            portHistoryRows: number;
            reminders: components["schemas"]["ReminderOperationsStatus"];
            /** Format: int64 */
            resolvedNotificationRows: number;
            wxPusher: components["schemas"]["WxPusherOperationsStatus"];
        };
        PortHistoryMetrics: {
            /** Format: int64 */
            averageSessionSeconds: number | null;
            completedSessions: number;
            /** Format: int64 */
            gapSeconds: number;
            /** Format: int64 */
            idleSeconds: number;
            /** Format: int64 */
            inUseSeconds: number;
            /** Format: int64 */
            observedSeconds: number;
            /** Format: double */
            occupancyPercent: number | null;
            /** Format: int64 */
            offlineSeconds: number;
            sampleState: components["schemas"]["HistorySampleState"];
        };
        PortHistoryResponse: {
            currentStatus: components["schemas"]["PortStatus"];
            daily: components["schemas"]["HistoryDailyPoint"][];
            device: components["schemas"]["HistoryDevice"];
            historyNotice: string;
            /** Format: date-time */
            historyStartedAt?: string;
            metrics: components["schemas"]["PortHistoryMetrics"];
            portId: number;
            timeline: components["schemas"]["PortHistoryTimelineItem"][];
            timelineTruncated: boolean;
            window: components["schemas"]["HistoryWindow"];
        };
        PortHistorySummary: {
            currentStatus: components["schemas"]["PortStatus"];
            /** Format: date-time */
            historyStartedAt?: string;
            metrics: components["schemas"]["PortHistoryMetrics"];
            portId: number;
        };
        PortHistoryTimelineItem: {
            /** Format: date-time */
            changedAt: string;
            fromStatus?: components["schemas"]["PortStatus"];
            portId: number;
            remainingText?: string;
            toStatus: components["schemas"]["PortStatus"];
            usedSeconds: number;
        };
        /** @enum {string} */
        PortStatus: "idle" | "in_use" | "offline";
        RegistrationSettings: {
            backgroundRemindersEnabled: boolean;
            defaultDeviceLimit: number;
            defaultRefreshEnabled: boolean;
            inviteRequired: boolean;
            notificationRetentionDays: number;
            openRegistration: boolean;
            portHistoryRetentionDays: number;
            powerRestoreJitterMinutes: number;
            /**
             * @deprecated
             * @description 旧客户端兼容字段，固定返回 false；固定时段提醒已停止调度，原配置仅保留用于回滚。
             */
            readonly recurringRemindersEnabled: boolean;
            scheduledPowerOffEnabled: boolean;
            scheduledPowerOffEndMinute: number;
            scheduledPowerOffStartMinute: number;
            scheduledPowerOffTimezone: string;
            statsRetentionDays: number;
            watchDailyRefreshQuota: number;
            watchPileLimitPerUser: number;
            watchRefreshIntervalMinutes: number;
        };
        ReminderOperationsStatus: {
            activeTemporaryRules: number;
            /**
             * Format: double
             * @description 过去 24 小时已结束临时提醒的平均运行分钟数。
             */
            averageTemporaryMinutes: number;
            cacheHits24Hours: number;
            coalesced24Hours: number;
            completedExpired24Hours: number;
            completedNotified24Hours: number;
            duePiles: number;
            enabled: boolean;
            inFlightPiles: number;
            maxConsecutiveFailures: number;
            message: string;
            /** Format: date-time */
            nextAttemptAt?: string | null;
            quotaSkips24Hours: number;
            remoteAttempts24Hours: number;
            remoteFailures24Hours: number;
            remoteSuccesses24Hours: number;
            /** Format: double */
            remoteSuccessRate24Hours: number;
            scheduledPowerOffActive: boolean;
            schedulerErrors24Hours: number;
            schedulerRunning: boolean;
            /** @enum {string} */
            state: "healthy" | "degraded" | "disabled" | "power_off" | "stopped";
            trackedPiles: number;
        };
        UpdatedCount: {
            /** Format: int64 */
            updated: number;
        };
        /** @enum {string} */
        WatchCompletionReason: "notified" | "expired" | "cancelled";
        WatchOverview: {
            accountRefreshEnabled: boolean;
            backgroundRemindersEnabled: boolean;
            dailyQuotaLimit: number;
            dailyQuotaUsed: number;
            /** Format: date */
            quotaDate: string;
            refreshIntervalMinutes: number;
            reminderPileCount: number;
            reminderPileLimit: number;
            scheduledPowerOffEnabled: boolean;
            scheduledPowerOffEndMinute: number;
            scheduledPowerOffStartMinute: number;
            scheduledPowerOffTimezone: string;
        };
        WatchRule: {
            /** @description 当地时区当天结束分钟；小于起始分钟时表示跨午夜。 */
            activeEndMinute: number;
            /** @description 当地时区当天起始分钟；与结束分钟相同时表示全天。 */
            activeStartMinute: number;
            /** @description 星期位掩码，bit 0 至 bit 6 依次代表周一至周日。 */
            activeWeekdays: number;
            /** Format: date-time */
            completedAt?: string;
            completionReason?: components["schemas"]["WatchCompletionReason"];
            /** Format: date-time */
            createdAt: string;
            deviceId: string;
            enabled: boolean;
            /** @description 在过期或计划断电前预计最多还会执行的整桩后台检查次数。 */
            estimatedRemainingChecks?: number;
            /**
             * Format: date-time
             * @description 临时提醒的硬截止时间；旧固定规则不返回。
             */
            expiresAt?: string;
            id: string;
            mode: components["schemas"]["WatchRuleMode"];
            /**
             * Format: date-time
             * @description 当前活动提醒预计下次后台检查时间。
             */
            nextCheckAt?: string;
            /** @description 临时提醒固定为 true；旧固定规则固定为 false。 */
            stopAfterNotify: boolean;
            timezone: string;
            /** Format: date-time */
            updatedAt: string;
            userId: string;
        };
        WatchRuleCreateRequest: {
            deviceId: string;
            /** @description 省略时使用 2h，且服务端会将截止时间限制在当天计划断电开始前。 */
            duration?: components["schemas"]["WatchTemporaryDuration"];
        };
        WatchRuleCreateResult: {
            backgroundScheduled: boolean;
            idlePortIds: number[];
            message: string;
            rule?: components["schemas"]["WatchRule"];
        };
        /**
         * @description temporary 是当前按需提醒；recurring 仅用于读取升级前保留的已停用规则，不能新建或编辑。
         * @enum {string}
         */
        WatchRuleMode: "temporary" | "recurring";
        WatchRuleUpdateRequest: {
            /** @description true 表示将活动临时提醒原子标记为 cancelled。 */
            cancel?: boolean;
            duration?: components["schemas"]["WatchTemporaryDuration"];
        };
        /** @enum {string} */
        WatchTemporaryDuration: "1h" | "2h" | "4h" | "until_power_off";
        WxPusherBindSession: {
            /** Format: date-time */
            completedAt?: string;
            errorCode?: components["schemas"]["WxPusherErrorCode"];
            /** Format: date-time */
            expiresAt: string;
            id: string;
            message: string;
            /**
             * Format: date-time
             * @description 前端不得在此时间前再次查询绑定进度。
             */
            nextPollAt: string;
            /**
             * Format: uri
             * @description 仅 waiting_scan 状态返回的官方 HTTPS 二维码地址。
             */
            qrUrl?: string;
            status: components["schemas"]["WxPusherBindSessionStatus"];
        };
        /** @enum {string} */
        WxPusherBindSessionStatus: "waiting_scan" | "bound" | "expired" | "failed";
        WxPusherChannelState: {
            bound: boolean;
            /** Format: date-time */
            boundAt?: string;
            /** @description 服务端是否配置 AppToken；AppToken 本身永不返回。 */
            configured: boolean;
            /** @description 提醒用户在 WxPusher App 或微信中确认是否收到；平台无法确认消息是否已读。 */
            deliveryDisclaimer: string;
            enabled: boolean;
            eventTypes: components["schemas"]["WxPusherEventType"][];
            /** @description 最近一次正式通知投递结果。 */
            lastDelivery?: components["schemas"]["NotificationDeliverySummary"];
            /** Format: date-time */
            lastTestAt?: string;
            /** @description 最近一次测试消息投递结果。 */
            lastTestDelivery?: components["schemas"]["NotificationDeliverySummary"];
            /** @description 仅用于帮助用户识别绑定，不返回完整 UID。 */
            maskedUid?: string;
        };
        WxPusherChannelUpdateRequest: {
            enabled?: boolean;
            eventTypes?: components["schemas"]["WxPusherEventType"][];
        };
        /** @enum {string} */
        WxPusherErrorCode: "rate_limited" | "invalid_token" | "invalid_uid" | "recipient_rejected" | "provider_unavailable" | "timeout" | "invalid_response" | "ambiguous_result" | "storage_unavailable";
        /** @enum {string} */
        WxPusherEventType: "pile_available" | "credential_expired" | "pile_offline" | "pile_recovered";
        WxPusherOperationsStatus: {
            /** Format: double */
            acceptanceRate24Hours: number;
            accepted24Hours: number;
            /** @description 已被供应商受理、仍等待状态确认的投递数。 */
            acceptedPendingDeliveries: number;
            activeBindings: number;
            affectedBindingUsers: number;
            attempts24Hours: number;
            bindingFailures24Hours: number;
            configured: boolean;
            consecutiveSystemFailures: number;
            dispatcherRunning: boolean;
            failedDeliveries: number;
            /** Format: date-time */
            lastAcceptedAt?: string | null;
            /** @enum {string|null} */
            lastErrorCategory?: "configuration" | "rate_limited" | "provider_unavailable" | "delivery_unconfirmed" | "binding_invalid" | "internal" | null;
            /** Format: date-time */
            lastFailureAt?: string | null;
            /** Format: date-time */
            lastProviderSuccessAt?: string | null;
            message: string;
            /** Format: date-time */
            oldestPendingAt?: string | null;
            pendingDeliveries: number;
            providerSucceeded24Hours: number;
            /** Format: double */
            providerSuccessRate24Hours: number;
            retryingDeliveries: number;
            sendingDeliveries: number;
            /** @enum {string} */
            state: "healthy" | "degraded" | "disabled" | "stopped";
            systemFailures24Hours: number;
            uncertainDeliveries: number;
        };
    };
    responses: {
        /** @description 当前账户不是管理员 */
        AdminRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "admin permission required"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 指标或状态历史聚合暂时不可用 */
        AdminTrendsUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "ADMIN_TRENDS_UNAVAILABLE",
                 *       "error": "运营趋势暂时不可用，请稍后重试"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 设备不属于当前用户、端口不存在或尚无该端口历史 */
        HistoryNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "HISTORY_NOT_FOUND",
                 *       "error": "未找到对应的历史记录"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 所选范围内的状态变化超过单次分析上限 */
        HistoryRangeTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "HISTORY_RANGE_TOO_LARGE",
                 *       "error": "该范围内历史变化过多，请缩短查询范围"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 历史存储或聚合暂时不可用 */
        HistoryUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "HISTORY_UNAVAILABLE",
                 *       "error": "历史数据暂时不可用，请稍后重试"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 趋势范围或时区参数无效 */
        InvalidAdminTrendQuery: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "ADMIN_TREND_QUERY_INVALID",
                 *       "error": "趋势范围或时区参数无效"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 设备 ID、历史范围或时区参数无效 */
        InvalidHistoryQuery: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 设备 ID、端口编号、历史范围或时区参数无效 */
        InvalidPortHistoryQuery: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 请求方法不受支持 */
        MethodNotAllowed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "method not allowed"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 通知不存在或不属于当前用户 */
        NotificationNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOTIFICATION_NOT_FOUND",
                 *       "error": "未找到通知"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 通知偏好、免打扰时间或时区无效 */
        NotificationPreferenceInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOTIFICATION_PREFERENCE_INVALID",
                 *       "error": "通知偏好内容无效"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 通知状态、分页大小或游标无效 */
        NotificationQueryInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOTIFICATION_QUERY_INVALID",
                 *       "error": "通知筛选或分页参数无效"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 通知存储暂时不可用 */
        NotificationUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOTIFICATION_UNAVAILABLE",
                 *       "error": "通知功能暂时不可用，请稍后重试"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 当前账户不是普通用户 */
        OrdinaryUserRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "ordinary user permission required"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 未登录或会话已失效 */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "login required"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 目标已存在，或达到规则/提醒桩数量限制 */
        WatchConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 空闲提醒规则字段、星期、时段或时区无效 */
        WatchInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "WATCH_RULE_INVALID",
                 *       "error": "空闲提醒规则内容无效"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 规则不存在或不属于当前用户 */
        WatchRuleNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "WATCH_RULE_NOT_FOUND",
                 *       "error": "未找到空闲提醒规则"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 充电桩不属于当前用户 */
        WatchTargetNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "WATCH_TARGET_NOT_FOUND",
                 *       "error": "未找到当前账户下的充电桩"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 空闲提醒规则存储暂时不可用 */
        WatchUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "WATCH_UNAVAILABLE",
                 *       "error": "空闲提醒功能暂时不可用，请稍后重试"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 当前用户已有活动会话，或该 UID 已绑定其他 Charge Console 账户 */
        WxPusherBindingConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 绑定会话不存在、已清理或不属于当前用户 */
        WxPusherBindSessionNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "WXPUSHER_BIND_SESSION_NOT_FOUND",
                 *       "error": "未找到绑定会话"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 当前用户尚未绑定 WxPusher，或微信提醒处于关闭状态 */
        WxPusherChannelConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description WxPusher 通道开关或事件类型设置无效 */
        WxPusherInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "WXPUSHER_INVALID",
                 *       "error": "WxPusher 提醒设置无效"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 创建二维码或发送测试消息过于频繁 */
        WxPusherRateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "WXPUSHER_RATE_LIMITED",
                 *       "error": "操作过于频繁，请稍后再试"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description WxPusher 未配置、存储不可用或服务暂时异常；通知中心不受影响 */
        WxPusherUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description 趋势统计范围；省略时使用 24h */
        AdminTrendRange: components["schemas"]["AdminTrendRange"];
        /** @description 当前用户已绑定的 6–64 位数字设备 ID */
        DeviceId: string;
        /** @description 历史统计范围；省略时使用 7d */
        HistoryRange: components["schemas"]["HistoryRange"];
        /** @description 当前用户通知 ID */
        NotificationId: string;
        /** @description 充电口编号 */
        PortId: number;
        /** @description IANA 时区名称；省略时使用 Asia/Shanghai */
        Timezone: string;
        /** @description 当前用户空闲提醒规则 ID */
        WatchRuleId: string;
        /** @description 当前用户的随机绑定会话 ID */
        WxPusherBindSessionId: string;
    };
    requestBodies: never;
    headers: {
        /** @description 包含范围和导出日期的安全 ASCII 文件名 */
        CSVContentDisposition: string;
        /** @description 分析响应包含用户或运营数据，不允许共享或本地缓存 */
        PrivateNoStore: "private, no-store";
    };
    pathItems: never;
}
export type AdminTrendPoint = components['schemas']['AdminTrendPoint'];
export type AdminTrendRange = components['schemas']['AdminTrendRange'];
export type AdminTrendsResponse = components['schemas']['AdminTrendsResponse'];
export type AdminTrendSummary = components['schemas']['AdminTrendSummary'];
export type AdminTrendWindow = components['schemas']['AdminTrendWindow'];
export type CodedErrorResponse = components['schemas']['CodedErrorResponse'];
export type DeletedCount = components['schemas']['DeletedCount'];
export type DeviceHistoryResponse = components['schemas']['DeviceHistoryResponse'];
export type ErrorResponse = components['schemas']['ErrorResponse'];
export type HistoryDailyPoint = components['schemas']['HistoryDailyPoint'];
export type HistoryDevice = components['schemas']['HistoryDevice'];
export type HistoryHeatmapCell = components['schemas']['HistoryHeatmapCell'];
export type HistoryHourInsight = components['schemas']['HistoryHourInsight'];
export type HistoryRange = components['schemas']['HistoryRange'];
export type HistorySampleState = components['schemas']['HistorySampleState'];
export type HistoryWindow = components['schemas']['HistoryWindow'];
export type Notification = components['schemas']['Notification'];
export type NotificationDeliveryStatus = components['schemas']['NotificationDeliveryStatus'];
export type NotificationDeliverySummary = components['schemas']['NotificationDeliverySummary'];
export type NotificationDeliveryUserState = components['schemas']['NotificationDeliveryUserState'];
export type NotificationPage = components['schemas']['NotificationPage'];
export type NotificationPreference = components['schemas']['NotificationPreference'];
export type NotificationPreferenceUpdateRequest = components['schemas']['NotificationPreferenceUpdateRequest'];
export type NotificationSeverity = components['schemas']['NotificationSeverity'];
export type NotificationStatusFilter = components['schemas']['NotificationStatusFilter'];
export type NotificationType = components['schemas']['NotificationType'];
export type OperationsStatus = components['schemas']['OperationsStatus'];
export type PortHistoryMetrics = components['schemas']['PortHistoryMetrics'];
export type PortHistoryResponse = components['schemas']['PortHistoryResponse'];
export type PortHistorySummary = components['schemas']['PortHistorySummary'];
export type PortHistoryTimelineItem = components['schemas']['PortHistoryTimelineItem'];
export type PortStatus = components['schemas']['PortStatus'];
export type RegistrationSettings = components['schemas']['RegistrationSettings'];
export type ReminderOperationsStatus = components['schemas']['ReminderOperationsStatus'];
export type UpdatedCount = components['schemas']['UpdatedCount'];
export type WatchCompletionReason = components['schemas']['WatchCompletionReason'];
export type WatchOverview = components['schemas']['WatchOverview'];
export type WatchRule = components['schemas']['WatchRule'];
export type WatchRuleCreateRequest = components['schemas']['WatchRuleCreateRequest'];
export type WatchRuleCreateResult = components['schemas']['WatchRuleCreateResult'];
export type WatchRuleMode = components['schemas']['WatchRuleMode'];
export type WatchRuleUpdateRequest = components['schemas']['WatchRuleUpdateRequest'];
export type WatchTemporaryDuration = components['schemas']['WatchTemporaryDuration'];
export type WxPusherBindSession = components['schemas']['WxPusherBindSession'];
export type WxPusherBindSessionStatus = components['schemas']['WxPusherBindSessionStatus'];
export type WxPusherChannelState = components['schemas']['WxPusherChannelState'];
export type WxPusherChannelUpdateRequest = components['schemas']['WxPusherChannelUpdateRequest'];
export type WxPusherErrorCode = components['schemas']['WxPusherErrorCode'];
export type WxPusherEventType = components['schemas']['WxPusherEventType'];
export type WxPusherOperationsStatus = components['schemas']['WxPusherOperationsStatus'];
export type ResponseAdminRequired = components['responses']['AdminRequired'];
export type ResponseAdminTrendsUnavailable = components['responses']['AdminTrendsUnavailable'];
export type ResponseHistoryNotFound = components['responses']['HistoryNotFound'];
export type ResponseHistoryRangeTooLarge = components['responses']['HistoryRangeTooLarge'];
export type ResponseHistoryUnavailable = components['responses']['HistoryUnavailable'];
export type ResponseInvalidAdminTrendQuery = components['responses']['InvalidAdminTrendQuery'];
export type ResponseInvalidHistoryQuery = components['responses']['InvalidHistoryQuery'];
export type ResponseInvalidPortHistoryQuery = components['responses']['InvalidPortHistoryQuery'];
export type ResponseMethodNotAllowed = components['responses']['MethodNotAllowed'];
export type ResponseNotificationNotFound = components['responses']['NotificationNotFound'];
export type ResponseNotificationPreferenceInvalid = components['responses']['NotificationPreferenceInvalid'];
export type ResponseNotificationQueryInvalid = components['responses']['NotificationQueryInvalid'];
export type ResponseNotificationUnavailable = components['responses']['NotificationUnavailable'];
export type ResponseOrdinaryUserRequired = components['responses']['OrdinaryUserRequired'];
export type ResponseUnauthenticated = components['responses']['Unauthenticated'];
export type ResponseWatchConflict = components['responses']['WatchConflict'];
export type ResponseWatchInvalid = components['responses']['WatchInvalid'];
export type ResponseWatchRuleNotFound = components['responses']['WatchRuleNotFound'];
export type ResponseWatchTargetNotFound = components['responses']['WatchTargetNotFound'];
export type ResponseWatchUnavailable = components['responses']['WatchUnavailable'];
export type ResponseWxPusherBindingConflict = components['responses']['WxPusherBindingConflict'];
export type ResponseWxPusherBindSessionNotFound = components['responses']['WxPusherBindSessionNotFound'];
export type ResponseWxPusherChannelConflict = components['responses']['WxPusherChannelConflict'];
export type ResponseWxPusherInvalid = components['responses']['WxPusherInvalid'];
export type ResponseWxPusherRateLimited = components['responses']['WxPusherRateLimited'];
export type ResponseWxPusherUnavailable = components['responses']['WxPusherUnavailable'];
export type ParameterAdminTrendRange = components['parameters']['AdminTrendRange'];
export type ParameterDeviceId = components['parameters']['DeviceId'];
export type ParameterHistoryRange = components['parameters']['HistoryRange'];
export type ParameterNotificationId = components['parameters']['NotificationId'];
export type ParameterPortId = components['parameters']['PortId'];
export type ParameterTimezone = components['parameters']['Timezone'];
export type ParameterWatchRuleId = components['parameters']['WatchRuleId'];
export type ParameterWxPusherBindSessionId = components['parameters']['WxPusherBindSessionId'];
export type HeaderCsvContentDisposition = components['headers']['CSVContentDisposition'];
export type HeaderPrivateNoStore = components['headers']['PrivateNoStore'];
export type $defs = Record<string, never>;
export interface operations {
    getAdminOperations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前运维状态和过去 24 小时提醒调度指标 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationsStatus"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["AdminRequired"];
            405: components["responses"]["MethodNotAllowed"];
            /** @description 数据库运维信息暂时不可用 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAdminSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前完整系统策略 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationSettings"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["AdminRequired"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    updateAdminSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrationSettings"];
            };
        };
        responses: {
            /** @description 保存后的完整系统策略 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationSettings"];
                };
            };
            /** @description 参数范围或时区无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["AdminRequired"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    getAdminTrends: {
        parameters: {
            query?: {
                /** @description 趋势统计范围；省略时使用 24h */
                range?: components["parameters"]["AdminTrendRange"];
                /** @description IANA 时区名称；省略时使用 Asia/Shanghai */
                timezone?: components["parameters"]["Timezone"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求量、远端成功率、活跃用户和离线端口趋势 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTrendsResponse"];
                };
            };
            400: components["responses"]["InvalidAdminTrendQuery"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["AdminRequired"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["AdminTrendsUnavailable"];
        };
    };
    exportAdminTrendsCSV: {
        parameters: {
            query?: {
                /** @description 趋势统计范围；省略时使用 24h */
                range?: components["parameters"]["AdminTrendRange"];
                /** @description IANA 时区名称；省略时使用 Asia/Shanghai */
                timezone?: components["parameters"]["Timezone"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 与相同范围趋势接口数值一致的 UTF-8 BOM CSV 文件 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    "Content-Disposition": components["headers"]["CSVContentDisposition"];
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            400: components["responses"]["InvalidAdminTrendQuery"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["AdminRequired"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["AdminTrendsUnavailable"];
        };
    };
    getWxPusherChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 配置可用性、绑定状态、事件偏好和最近投递结果；不返回完整 UID 或 AppToken */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WxPusherChannelState"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["WxPusherUnavailable"];
        };
    };
    deleteWxPusherChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已解除绑定；重复调用同样成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["WxPusherUnavailable"];
        };
    };
    updateWxPusherChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WxPusherChannelUpdateRequest"];
            };
        };
        responses: {
            /** @description 更新后的通道状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WxPusherChannelState"];
                };
            };
            400: components["responses"]["WxPusherInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            405: components["responses"]["MethodNotAllowed"];
            409: components["responses"]["WxPusherChannelConflict"];
            503: components["responses"]["WxPusherUnavailable"];
        };
    };
    createWxPusherBindSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 等待扫码的绑定会话；Provider code 不对前端公开 */
            201: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WxPusherBindSession"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            405: components["responses"]["MethodNotAllowed"];
            409: components["responses"]["WxPusherBindingConflict"];
            429: components["responses"]["WxPusherRateLimited"];
            503: components["responses"]["WxPusherUnavailable"];
        };
    };
    getWxPusherBindSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 当前用户的随机绑定会话 ID */
                sessionId: components["parameters"]["WxPusherBindSessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 等待扫码、已绑定、已过期或失败状态 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WxPusherBindSession"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            404: components["responses"]["WxPusherBindSessionNotFound"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["WxPusherUnavailable"];
        };
    };
    testWxPusherChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 测试投递已进入持久队列 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationDeliverySummary"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            405: components["responses"]["MethodNotAllowed"];
            409: components["responses"]["WxPusherChannelConflict"];
            429: components["responses"]["WxPusherRateLimited"];
            503: components["responses"]["WxPusherUnavailable"];
        };
    };
    recheckWxPusherTestDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 重新查询后的测试投递状态 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationDeliverySummary"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            /** @description 当前用户没有测试投递记录 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["WxPusherUnavailable"];
        };
    };
    getNotificationPreference: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 浏览器通知意愿与免打扰设置 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreference"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["NotificationUnavailable"];
        };
    };
    updateNotificationPreference: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationPreferenceUpdateRequest"];
            };
        };
        responses: {
            /** @description 更新后的通知偏好 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreference"];
                };
            };
            400: components["responses"]["NotificationPreferenceInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["NotificationUnavailable"];
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                status?: components["schemas"]["NotificationStatusFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 通知分页、下一游标和总未读数量 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPage"];
                };
            };
            400: components["responses"]["NotificationQueryInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["NotificationUnavailable"];
        };
    };
    markNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 当前用户通知 ID */
                notificationId: components["parameters"]["NotificationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已读后的通知 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            404: components["responses"]["NotificationNotFound"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["NotificationUnavailable"];
        };
    };
    markAllNotificationsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 实际更新数量 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdatedCount"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["NotificationUnavailable"];
        };
    };
    deleteResolvedNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 实际删除数量 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedCount"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["NotificationUnavailable"];
        };
    };
    getDeviceHistory: {
        parameters: {
            query?: {
                /** @description 历史统计范围；省略时使用 7d */
                range?: components["parameters"]["HistoryRange"];
                /** @description IANA 时区名称；省略时使用 Asia/Shanghai */
                timezone?: components["parameters"]["Timezone"];
            };
            header?: never;
            path: {
                /** @description 当前用户已绑定的 6–64 位数字设备 ID */
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 设备维度的历史指标、每日趋势、热力图和端口摘要 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceHistoryResponse"];
                };
            };
            400: components["responses"]["InvalidHistoryQuery"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            404: components["responses"]["HistoryNotFound"];
            405: components["responses"]["MethodNotAllowed"];
            422: components["responses"]["HistoryRangeTooLarge"];
            503: components["responses"]["HistoryUnavailable"];
        };
    };
    getPortHistory: {
        parameters: {
            query?: {
                /** @description 历史统计范围；省略时使用 7d */
                range?: components["parameters"]["HistoryRange"];
                /** @description IANA 时区名称；省略时使用 Asia/Shanghai */
                timezone?: components["parameters"]["Timezone"];
            };
            header?: never;
            path: {
                /** @description 当前用户已绑定的 6–64 位数字设备 ID */
                deviceId: components["parameters"]["DeviceId"];
                /** @description 充电口编号 */
                portId: components["parameters"]["PortId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 单个端口的历史指标、每日趋势和最近状态时间线 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortHistoryResponse"];
                };
            };
            400: components["responses"]["InvalidPortHistoryQuery"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            404: components["responses"]["HistoryNotFound"];
            405: components["responses"]["MethodNotAllowed"];
            422: components["responses"]["HistoryRangeTooLarge"];
            503: components["responses"]["HistoryUnavailable"];
        };
    };
    getWatchOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 仅包含当前用户用量和管理员公开给普通用户的提醒策略 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchOverview"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["WatchUnavailable"];
        };
    };
    listWatchRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 按更新时间倒序返回的空闲提醒规则 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchRule"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["WatchUnavailable"];
        };
    };
    createWatchRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchRuleCreateRequest"];
            };
        };
        responses: {
            /** @description 首次整桩检查结果；无空闲口时包含已创建的临时提醒 */
            201: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchRuleCreateResult"];
                };
            };
            400: components["responses"]["WatchInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            404: components["responses"]["WatchTargetNotFound"];
            405: components["responses"]["MethodNotAllowed"];
            409: components["responses"]["WatchConflict"];
            503: components["responses"]["WatchUnavailable"];
        };
    };
    deleteWatchRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 当前用户空闲提醒规则 ID */
                ruleId: components["parameters"]["WatchRuleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 空闲提醒规则已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            404: components["responses"]["WatchRuleNotFound"];
            405: components["responses"]["MethodNotAllowed"];
            503: components["responses"]["WatchUnavailable"];
        };
    };
    updateWatchRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 当前用户空闲提醒规则 ID */
                ruleId: components["parameters"]["WatchRuleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchRuleUpdateRequest"];
            };
        };
        responses: {
            /** @description 更新后的空闲提醒规则 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchRule"];
                };
            };
            400: components["responses"]["WatchInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            404: components["responses"]["WatchRuleNotFound"];
            405: components["responses"]["MethodNotAllowed"];
            409: components["responses"]["WatchConflict"];
            503: components["responses"]["WatchUnavailable"];
        };
    };
}
