/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/piles/{deviceId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取充电桩历史分析 */
        get: operations["getDeviceHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/piles/{deviceId}/ports/{portId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取单个充电口历史分析 */
        get: operations["getPortHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CodedErrorResponse: {
            /** @enum {string} */
            code: "DEVICE_ID_INVALID" | "PORT_ID_INVALID" | "HISTORY_QUERY_INVALID" | "HISTORY_NOT_FOUND" | "HISTORY_RANGE_TOO_LARGE" | "HISTORY_UNAVAILABLE";
            error: string;
        };
        DeviceHistoryResponse: {
            busiestHours: components["schemas"]["HistoryHourInsight"][];
            daily: components["schemas"]["HistoryDailyPoint"][];
            device: components["schemas"]["HistoryDevice"];
            heatmap: components["schemas"]["HistoryHeatmapCell"][];
            historyNotice: string;
            /** Format: date-time */
            historyStartedAt?: string;
            metrics: components["schemas"]["PortHistoryMetrics"];
            ports: components["schemas"]["PortHistorySummary"][];
            quietSuggestion?: components["schemas"]["HistoryHourInsight"];
            window: components["schemas"]["HistoryWindow"];
        };
        ErrorResponse: {
            error: string;
        };
        HistoryDailyPoint: {
            /** Format: date */
            date: string;
            metrics: components["schemas"]["PortHistoryMetrics"];
        };
        HistoryDevice: {
            address: string;
            id: string;
            name: string;
            number: string;
        };
        HistoryHeatmapCell: {
            hour: number;
            /** Format: int64 */
            idleSeconds: number;
            /** Format: int64 */
            inUseSeconds: number;
            /** Format: double */
            occupancyPercent: number | null;
            /** Format: int64 */
            offlineSeconds: number;
            sampleDates: number;
            sampleSufficient: boolean;
            weekday: number;
        };
        HistoryHourInsight: {
            hour: number;
            /** Format: double */
            occupancyPercent: number;
            sampleDates: number;
            weekday: number;
        };
        /**
         * @default 7d
         * @enum {string}
         */
        HistoryRange: "24h" | "7d" | "30d";
        /** @enum {string} */
        HistorySampleState: "no_data" | "insufficient" | "partial" | "sufficient";
        HistoryWindow: {
            /** Format: date-time */
            end: string;
            range: components["schemas"]["HistoryRange"];
            /** Format: date-time */
            start: string;
            timezone: string;
        };
        PortHistoryMetrics: {
            /** Format: int64 */
            averageSessionSeconds: number | null;
            completedSessions: number;
            /** Format: int64 */
            gapSeconds: number;
            /** Format: int64 */
            idleSeconds: number;
            /** Format: int64 */
            inUseSeconds: number;
            /** Format: int64 */
            observedSeconds: number;
            /** Format: double */
            occupancyPercent: number | null;
            /** Format: int64 */
            offlineSeconds: number;
            sampleState: components["schemas"]["HistorySampleState"];
        };
        PortHistoryResponse: {
            currentStatus: components["schemas"]["PortStatus"];
            daily: components["schemas"]["HistoryDailyPoint"][];
            device: components["schemas"]["HistoryDevice"];
            historyNotice: string;
            /** Format: date-time */
            historyStartedAt?: string;
            metrics: components["schemas"]["PortHistoryMetrics"];
            portId: number;
            timeline: components["schemas"]["PortHistoryTimelineItem"][];
            timelineTruncated: boolean;
            window: components["schemas"]["HistoryWindow"];
        };
        PortHistorySummary: {
            currentStatus: components["schemas"]["PortStatus"];
            /** Format: date-time */
            historyStartedAt?: string;
            metrics: components["schemas"]["PortHistoryMetrics"];
            portId: number;
        };
        PortHistoryTimelineItem: {
            /** Format: date-time */
            changedAt: string;
            fromStatus?: components["schemas"]["PortStatus"];
            portId: number;
            remainingText?: string;
            toStatus: components["schemas"]["PortStatus"];
            usedSeconds: number;
        };
        /** @enum {string} */
        PortStatus: "idle" | "in_use" | "offline";
    };
    responses: {
        /** @description 设备不属于当前用户、端口不存在或尚无该端口历史 */
        HistoryNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "HISTORY_NOT_FOUND",
                 *       "error": "未找到对应的历史记录"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 所选范围内的状态变化超过单次分析上限 */
        HistoryRangeTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "HISTORY_RANGE_TOO_LARGE",
                 *       "error": "该范围内历史变化过多，请缩短查询范围"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 历史存储或聚合暂时不可用 */
        HistoryUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "HISTORY_UNAVAILABLE",
                 *       "error": "历史数据暂时不可用，请稍后重试"
                 *     }
                 */
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 设备 ID、历史范围或时区参数无效 */
        InvalidHistoryQuery: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 设备 ID、端口编号、历史范围或时区参数无效 */
        InvalidPortHistoryQuery: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CodedErrorResponse"];
            };
        };
        /** @description 请求方法不受支持 */
        MethodNotAllowed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "method not allowed"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 当前账户不是普通用户 */
        OrdinaryUserRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "ordinary user permission required"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 未登录或会话已失效 */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "login required"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description 当前用户已绑定的 6–64 位数字设备 ID */
        DeviceId: string;
        /** @description 历史统计范围；省略时使用 7d */
        HistoryRange: components["schemas"]["HistoryRange"];
        /** @description 充电口编号 */
        PortId: number;
        /** @description IANA 时区名称；省略时使用 Asia/Shanghai */
        Timezone: string;
    };
    requestBodies: never;
    headers: {
        /** @description 历史响应包含用户数据，不允许共享或本地缓存 */
        PrivateNoStore: "private, no-store";
    };
    pathItems: never;
}
export type CodedErrorResponse = components['schemas']['CodedErrorResponse'];
export type DeviceHistoryResponse = components['schemas']['DeviceHistoryResponse'];
export type ErrorResponse = components['schemas']['ErrorResponse'];
export type HistoryDailyPoint = components['schemas']['HistoryDailyPoint'];
export type HistoryDevice = components['schemas']['HistoryDevice'];
export type HistoryHeatmapCell = components['schemas']['HistoryHeatmapCell'];
export type HistoryHourInsight = components['schemas']['HistoryHourInsight'];
export type HistoryRange = components['schemas']['HistoryRange'];
export type HistorySampleState = components['schemas']['HistorySampleState'];
export type HistoryWindow = components['schemas']['HistoryWindow'];
export type PortHistoryMetrics = components['schemas']['PortHistoryMetrics'];
export type PortHistoryResponse = components['schemas']['PortHistoryResponse'];
export type PortHistorySummary = components['schemas']['PortHistorySummary'];
export type PortHistoryTimelineItem = components['schemas']['PortHistoryTimelineItem'];
export type PortStatus = components['schemas']['PortStatus'];
export type ResponseHistoryNotFound = components['responses']['HistoryNotFound'];
export type ResponseHistoryRangeTooLarge = components['responses']['HistoryRangeTooLarge'];
export type ResponseHistoryUnavailable = components['responses']['HistoryUnavailable'];
export type ResponseInvalidHistoryQuery = components['responses']['InvalidHistoryQuery'];
export type ResponseInvalidPortHistoryQuery = components['responses']['InvalidPortHistoryQuery'];
export type ResponseMethodNotAllowed = components['responses']['MethodNotAllowed'];
export type ResponseOrdinaryUserRequired = components['responses']['OrdinaryUserRequired'];
export type ResponseUnauthenticated = components['responses']['Unauthenticated'];
export type ParameterDeviceId = components['parameters']['DeviceId'];
export type ParameterHistoryRange = components['parameters']['HistoryRange'];
export type ParameterPortId = components['parameters']['PortId'];
export type ParameterTimezone = components['parameters']['Timezone'];
export type HeaderPrivateNoStore = components['headers']['PrivateNoStore'];
export type $defs = Record<string, never>;
export interface operations {
    getDeviceHistory: {
        parameters: {
            query?: {
                /** @description 历史统计范围；省略时使用 7d */
                range?: components["parameters"]["HistoryRange"];
                /** @description IANA 时区名称；省略时使用 Asia/Shanghai */
                timezone?: components["parameters"]["Timezone"];
            };
            header?: never;
            path: {
                /** @description 当前用户已绑定的 6–64 位数字设备 ID */
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 设备维度的历史指标、每日趋势、热力图和端口摘要 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceHistoryResponse"];
                };
            };
            400: components["responses"]["InvalidHistoryQuery"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            404: components["responses"]["HistoryNotFound"];
            405: components["responses"]["MethodNotAllowed"];
            422: components["responses"]["HistoryRangeTooLarge"];
            503: components["responses"]["HistoryUnavailable"];
        };
    };
    getPortHistory: {
        parameters: {
            query?: {
                /** @description 历史统计范围；省略时使用 7d */
                range?: components["parameters"]["HistoryRange"];
                /** @description IANA 时区名称；省略时使用 Asia/Shanghai */
                timezone?: components["parameters"]["Timezone"];
            };
            header?: never;
            path: {
                /** @description 当前用户已绑定的 6–64 位数字设备 ID */
                deviceId: components["parameters"]["DeviceId"];
                /** @description 充电口编号 */
                portId: components["parameters"]["PortId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 单个端口的历史指标、每日趋势和最近状态时间线 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortHistoryResponse"];
                };
            };
            400: components["responses"]["InvalidPortHistoryQuery"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["OrdinaryUserRequired"];
            404: components["responses"]["HistoryNotFound"];
            405: components["responses"]["MethodNotAllowed"];
            422: components["responses"]["HistoryRangeTooLarge"];
            503: components["responses"]["HistoryUnavailable"];
        };
    };
}
